services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: airport
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e4r5t6y
    ports:
      - "15432:5432"
    volumes:
      - pgdata-18:/var/lib/postgresql/18/docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d airport"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 15s
      
  continentexpress.tt.api:
    image: continent-express-tt-api
    build:
      context: .
      dockerfile: Host/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - "5179:5179"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
  redis:
    image: redis/redis-stack:latest
    container_name: redis_container
    ports:
      - "6379:6379"
      - "8001:8001"
volumes:
  pgdata-18:

